export const items = [
  {
    id: 1,
    name: "cerelac",
    posterName: "John Doe",
    posterPhoneNumber: "555-123-4567",
    condition: "Good",
    date: "2023-01-05",
    price: "10",
    imageUrl: require("../../assets/itemsimages/image1.jfif"),
    category: "food",
  },
  {
    id: 2,
    name: "boy t-shirt and pants",
    posterName: "Jane Smith",
    posterPhoneNumber: "555-987-6543",
    condition: "Excellent",
    date: "2023-01-01",
    price: "15",
    imageUrl: require("../../assets/itemsimages/image2.jpg"),
    category: "clothes",
  },
  {
    id: 3,
    name: "cerelac",
    posterName: "Johnny Doe",
    posterPhoneNumber: "555-127-4567",
    condition: "Good",
    date: "2023-01-02",
    price: "12",
    imageUrl: require("../../assets/itemsimages/image3.png"),
    category: "food",
  },
];
